### PR TITLE
Fix Sileo Debian(s)

### PR DESCRIPTION
**Pull request by debouncedgit**
Split Alpha from Base Channel. (Alpha Channel)
Use Simplified PostInst from Bingner (keep Sources in /etc/apt/sileo.list.d/sileo-base.sources & sileo.sources) in Sileo and remove Elucubratus to replace with Memo Repository.

Change priority of Sileo to optional, as it is _not_ required.

### CODE REVIEW

**Comment by Diatrus** [comment]
No

**Comment by debouncedgit** [comment]
you make me sad

**Comment by Diatrus** [comment]
Priority should be “standard” or “important” anyways btw @sukarodo

**Comment by debouncedgit** [comment]
Shit. Thanks

**Pull request closed without merging**
